acme_blog_homepage:
    pattern:  /
    defaults: { _controller: AcmeBlogBundle:Page:index }
    requirements:
        _method: GET
        
acme_blog_about:
    pattern: /about
    defaults: { _controller: AcmeBlogBundle:Page:about }
    requirements:
        _method: GET
        
acme_blog_contact:
    pattern: /contact
    defaults: { _controller: AcmeBlogBundle:Page:contact }
    requirements:
        _method: GET|POST
        
acme_blog_blog_show:
    pattern: /{id}
    defaults: { _controller: AcmeBlogBundle:Blog:show }
    requirements:
        _method: GET
        id: \d+
        
acme_blog_comment_create:
    pattern: /comment/{blog_id}
    defaults: {_controller: AcmeBlogBundle:Comment:create }
    requirements:
        _method: POST
        blog_id: \d+