parameters:
#    acme_blog.example.class: Acme\BlogBundle\Example

services:
#    acme_blog.example:
#        class: %acme_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    acme_blog.twig.extension:
        class: Acme\BlogBundle\Twig\Extensions\AcmeBlogExtension
        tags:
            - { name: twig.extension }
    